---
title: "Project 1"
date: "2023-06-25"
author: "Spencer Williams"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Packages Needed
```{r packages, include=TRUE}
library(httr)
library(dplyr)
library(jsonlite)
library(rmarkdown)
library(tidyverse)
```

### Installing Stock Data from January 9
```{r intro, include=TRUE}
library(dplyr)
myData <- GET("https://api.polygon.io/v2/aggs/grouped/locale/us/market/stocks/2023-01-09?adjusted=true&apiKey=BnFt9sqaLWehzloLkpMtEeOG4WjAqkUc")
str(myData, max.level = 1)
parsedJan <- fromJSON(rawToChar(myData$content))
str(parsedJan, max.level = 1)
parsedJan$results %>% colnames()
```

### Making A Data Frame for January 9th Data
```{r dataframe, include=TRUE}
parsedJanDataFrame <- as.data.frame(parsedJan)
colnames(parsedJanDataFrame) <- c("Query", "Total_Request", "Adjusted", "Symbol", "Volume", "Volume_Weight", "Open", "Close", "High", "Low", "Timestamp", "Transactions", "Status", "Request_ID", "Count")
```

### Installing Stock Data from March 9
```{r intro2, include=TRUE}
library(dplyr)
myData2 <- GET("https://api.polygon.io/v2/aggs/grouped/locale/us/market/stocks/2023-03-09?adjusted=true&apiKey=BnFt9sqaLWehzloLkpMtEeOG4WjAqkUc")
str(myData2, max.level = 1)
parsedMar <- fromJSON(rawToChar(myData2$content))
str(parsedMar, max.level = 1)
parsedMar$results %>% colnames()
```

### Making A Data Frame for March 9th Data
```{r dataframe2, include=TRUE}
parsedMarDataFrame <- as.data.frame(parsedMar)
colnames(parsedMarDataFrame) <- c("Query", "Total_Request", "Adjusted", "Symbol", "Volume", "Volume_Weight", "Open", "Close", "High", "Low", "Timestamp", "Transactions", "Status", "Request_ID", "Count")
```

### Combining the Two Data Frames and Adding a Month Variable
```{r combine, include=FALSE}
library(tidyr)
parsedJanDataFrame %>% drop_na()
parsedJanDataFrame <- mutate(parsedJanDataFrame, Month = "January")
parsedMarDataFrame %>% drop_na()
parsedMarDataFrame <- mutate(parsedMarDataFrame, Month = "March")
parsedFullData <- full_join(parsedJanDataFrame, parsedMarDataFrame)
```

```{r view_combine, include=TRUE}
head(parsedFullData)
```

### Creating Contingency Table
